language: python
sudo: false
dist: bionic

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - check
    - libssl-dev
    - python3-pip
    - valgrind
    - gcc-5
    - libc++-dev
    - protobuf-compiler
    - libprotobuf-dev
    - libprotoc-dev
    - python-protobuf

cache:
  directories:
    - $HOME/libsodium
    - $HOME/libtrezor-crypto

python:
  - "3.7"

install:
  - ./travis-install-libsodium.sh
  - export PKG_CONFIG_PATH=$HOME/libsodium/lib/pkgconfig:$PKG_CONFIG_PATH
  - export LD_LIBRARY_PATH=$HOME/libsodium/lib:$LD_LIBRARY_PATH
  - pip install .[poc,dev]
  - pip install .[tcry]
  - python setup.py install_trezorlib

script:
  - PYTHONPATH=.:$PYTHONPATH ./test-travis.sh

